version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@pythonrag-maintainers"
    assignees:
      - "@pythonrag-maintainers"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "ruff"
          - "mypy"
          - "pre-commit"
        update-types:
          - "minor"
          - "patch"
      docs-dependencies:
        patterns:
          - "mkdocs*"
          - "mkdocstrings*"
        update-types:
          - "minor"
          - "patch"
      ai-dependencies:
        patterns:
          - "openai"
          - "anthropic"
          - "sentence-transformers"
          - "transformers"
          - "torch"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@pythonrag-maintainers"
    commit-message:
      prefix: "ci"
      include: "scope" 
